config/routes.rb
Rails.application.routes.draw do
  get 'checkout/empty_cart'

  resources :checkout
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates_uniqueness_of :product_id
  validates_length_of :product_id, :within => 1..20, :too_long => "pick a shorter id", :too_short => "pick a longer id"
  validates_length_of :product_name, :within => 1..128, :too_long => "pick a shorter name", :too_short => "pick a longer name"
  validates_length_of :product_price, :within => 1..18, :too_long => "pick a valid value", :too_short => "pick a valid value"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkout_controller.rb
require "json"
require 'ruk1'

class CheckoutController < ApplicationController
  def index
    @products = Product.all.order("product_id asc")

    if cookies[:cart].blank?
      cookies[:cart] = JSON.generate([])
    end
    @carts = JSON.parse(cookies[:cart])


    promotional_rules = [1,2]
    co = Ruk1::Checkout.new(promotional_rules)
    @carts.each do |item|
      item['quantity'].times do
         co.scan(item)
      end
    end

    @total_price = co.total
    @total_quantity = co.total_quantity
  end

  def create
    if cookies[:cart].blank?
      cookies[:cart] = JSON.generate([])
    end
    @carts = JSON.parse(cookies[:cart])

    product_id = params[:product_id]
    product_name = params[:product_name]
    product_price = params[:product_price]

    found_at = -1
    @carts.each_with_index do |cart, index|
      if cart['product_id'] == product_id
        found_at = index
      end
    end

    if found_at == -1
      @carts << {
        product_id: product_id,
        product_name: product_name,
        product_price: product_price.to_f,
        quantity: 1
      }
    else
      @carts[found_at]['quantity'] += 1
    end

    cookies[:cart] = @carts.to_json

    redirect_to checkout_index_path
  end

  def empty_cart
    cookies.delete :cart
    redirect_to checkout_index_path
  end

  def remove_item_on_cart
    redirect_to checkout_index_path
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @page_title       = 'Index'
    @page_description = 'Index page.'
    @page_keywords    = 'Index, Index, Index'
    @products = Product.all.order("updated_at desc")
  end

  def show
    @product = Product.find(params[:id])

    @page_title       = @product.product_name
    @page_description = @product.product_name + ' page.'
    @page_keywords    = @product.product_name
  end

  def new
    @products = Product.order("created_at desc").limit(3)
  end

  def create
    @product = Product.new(product_params)
    @product.save

    redirect_to new_product_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:product_id, :product_name, :product_price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/checkout/index.html.erb
<div class="container">
  <div class="py-5 text-center">
    <h2>Checkout</h2>
  </div>

  <div class="row">
    <div class="col-md-8 order-md-2 mb-8">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted"><%= link_to 'Products', products_path %></span>
        <span class="badge badge-secondary badge-pill"><%= @products.size %></span>
      </h4>
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-sm-4">
            <div class="card">
              <div class="card-header">
                <%= link_to product.product_name + ' - ' + product.product_id, product_path(product) %>
              </div>
              <div class="card-body">

                <p class="card-text">£<%= product.product_price %></p>
                <%= button_to '+', {:controller => "checkout", :action => "create", :product_id => product.product_id, :product_name=> product.product_name, :product_price=> product.product_price} , :method=>:post, class: 'btn btn-lg btn-block btn-primary' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </div>
    <div class="col-md-4 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart -
          <%= link_to 'Empty cart', checkout_empty_cart_path %></span>
        <span class="badge badge-secondary badge-pill"><%= @total_quantity %></span>
      </h4>
      <ul class="list-group mb-3">
        <% @carts.each do |cart| %>
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0"><%= cart['product_name'] %></h6>
              <small class="text-muted">Pid:
                <%= cart['product_id'] %>
                - Qty:
                <%= cart['quantity'] %>
                - Prc:
                <%= cart['product_price'] %></small>
            </div>
            <span class="text-muted">£<%= cart['product_price'] %></span>
          </li>
        <% end %>

        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo</h6>
          </div>
          <span class="text-success">-£{tu_tu_tinh_di_choi_da}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total</span>
          <strong>£<%= @total_price %></strong>
        </li>
      </ul>
    </div>

  </div>

</div>

app/views/layouts/_footer.html.erb
<footer class="my-5 pt-5 text-muted text-center text-small">
  <p class="mb-1">&copy;
    <%= Time.zone.now.year %>
    KrisLuu</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: 'Rurak 1 demo' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container">
  <div class="py-5 text-center">
    <h2>Products - <%= link_to 'Checkout', checkout_index_path %></h2>
  </div>

  <div class="row">
    <div class="col-md-12 order-md-2 mb-12">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Products -
          <%= link_to 'New product', new_product_path %></span>
        <span class="badge badge-secondary badge-pill"><%= @products.size %></span>
      </h4>
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-sm-3">
            <div class="card">
              <div class="card-header">
                <%= link_to product.product_name + ' - ' + product.product_id, product_path(product) %>
              </div>
              <div class="card-body">

                <p class="card-text">£<%= product.product_price %></p>
                <%= button_to 'Add to cart', {:controller => "checkout", :action => "create", :product_id => product.product_id, :product_name=> product.product_name, :product_price=> product.product_price} , :method=>:post, class: 'btn btn-lg btn-block btn-primary' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="py-5 text-center">
    <h2><%= link_to 'All products', products_path %>
      - New product</h2>

  </div>

  <div class="row">
    <div class="col-md-4 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Newest products</span>
      </h4>
      <ul class="list-group mb-3">
        <% @products.each do |product| %>
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0"><%= product.product_name %></h6>
              <small class="text-muted">Pid:
                <%= product.product_id %></small>
            </div>
            <span class="text-muted">£<%= product.product_price %></span>
          </li>
        <% end %>

      </ul>
    </div>
    <div class="col-md-8 order-md-1">
      <h4 class="mb-3">New product</h4>
      <%= form_with scope: :product, url: products_path, local: true do |form| %>
      <div class="mb-3">
        <label for="product_id">Product ID</label>
        <input type="text_field" class="form-control" name="product[product_id]">
      </div>
      <div class="mb-3">
        <label for="product_name">Product name</label>
        <input type="text_field" class="form-control" name="product[product_name]">
      </div>
      <div class="mb-3">
        <label for="product_price">Product price</label>
        <input type="text_field" class="form-control" name="product[product_price]">
      </div>
      <hr class="mb-4">
      <button class="btn btn-primary btn-lg btn-block" name="commit" type="submit">Add new product</button>

    <% end %>
  </div>
</div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="py-5 text-center">
    <h2><%= link_to 'All products', products_path %>
      - Details</h2>
  </div>
  <div class="card mb-4 shadow-sm">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal"><%= @product.product_id %>
        -
        <%= @product.product_name %></h4>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">£<%= @product.product_price %>
      </h1>
      <%= button_to 'Delete', {:controller => "products", :action => "destroy", :id => @product.id, :product_id => @product.product_id} , :method=>:delete, class: 'btn btn-lg btn-block btn-danger' %>

    </div>
  </div>
</div>